In [89]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [90]:
import numpy as np

##### Simple one dimensional numpy array with integers from 1 to 9

In [91]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], np.int32)
print(type(np_array))
print(np_array)
                

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


In [92]:
np_array_2d = np.array([[1, 2, 3, 12], [4, 5, 6, 11], [7, 8, 9, 10]])

np_array_2d


array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 10]])

In [93]:
np_array_2d.dtype

dtype('int32')

In [94]:
index_ = np_array_2d[0]
index_

array([ 1,  2,  3, 12])

In [95]:
maximum = np_array_2d.max()
maximum

12

In [96]:
minimum = np_array_2d.min()
minimum

1

In [97]:
sum_of_array = np_array_2d.sum()
sum_of_array

78

In [98]:
find_index = np.where(np_array_2d == 5)

print("Index of the number 5:", find_index)

Index of the number 5: (array([1], dtype=int64), array([1], dtype=int64))


In [99]:
i = np_array_2d[np_array_2d > 5]
i

array([12,  6, 11,  7,  8,  9, 10])

In [100]:
a = np_array_2d.shape

print("Shape of the array:", a)

Shape of the array: (3, 4)


In [101]:
size = np_array_2d.size
size

12

In [175]:
reshaped_array = np_array_2d.reshape(2, 6)
reshaped_array

array([[ 1,  2,  3, 12,  4,  5],
       [ 6, 11,  7,  8,  9, 10]])

In [176]:
reshaped_array = np.ravel(np_array_2d)
reshaped_array

array([ 1,  2,  3, 12,  4,  5,  6, 11,  7,  8,  9, 10])

In [177]:
reshaped_array = np_array_2d.ravel()
reshaped_array

array([ 1,  2,  3, 12,  4,  5,  6, 11,  7,  8,  9, 10])

In [172]:
np_array_2d

array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 10]])

#### Numpy Array Creation

In [103]:
listarray = [1, 2, 3, 4, 5]
np_array = np.array(listarray)
np_array

array([1, 2, 3, 4, 5])

 OR convert the dictionary to a list and then to an array using `np.array(list(dic_array.values()))` and its not for only dictionary its work with `set` and `tuple`


In [112]:
dic_array = {'a': 1, 'b': 2, 'c': 3}

np_array_from_dict = np.array(dic_array.values())

np_array_from_dict

array(dict_values([1, 2, 3]), dtype=object)

In [111]:
set_array = {1, 2, 3, 4, 5, 5}
np_array_from_set = np.array(set_array)
np_array_from_set

array({1, 2, 3, 4, 5}, dtype=object)

In [110]:
tuple_array = (1, 2, 3, 4, 5)
np_array_from_tuple = np.array(tuple_array)
np_array_from_tuple

array([1, 2, 3, 4, 5])

In [113]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [136]:
range_array = np.arange(10)
spa_range =  np.arange(1, 10, 2)

range_array, spa_range

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

In [128]:
linspace_array = np.linspace(1, 10, 5)
linspace_array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [164]:
empty_array = np.empty((2, 3))
empty_array

array([[4.24399158e-314, 2.54639495e-313, 1.06099790e-313],
       [2.33419537e-313, 1.69759663e-313, 2.12199579e-313]])

In [162]:
empty_array.fill(0)
empty_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [166]:
empty_like_array = np.empty_like(linspace_array)
empty_like_array

array([7.88152004e-312, 7.88213896e-312, 6.95246149e-310, 0.00000000e+000,
       0.00000000e+000])

In [167]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [168]:
with_num_array = np.identity(3)
with_num_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [169]:
with_num_array.shape

(3, 3)

In [170]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [102]:
match = np.where(np_array % 2 == 0)
match

(array([1, 3, 5, 7], dtype=int64),)

#### Numpy AIXS

In [178]:
x = [[1,2,3], [4,5,6], [7,8,9]]

np_x = np.array(x)
np_x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [184]:
sum_of_axis_0 = np_x.sum(axis=0)
sum_of_axis_0

array([12, 15, 18])

In [185]:
sum_of_axis_1 = np_x.sum(axis=1)
sum_of_axis_1

array([ 6, 15, 24])

In [186]:
tran_mat = np_x.T
tran_mat

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [187]:
np_x.flat

In [188]:
for item in np_x.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [189]:
dis = np_x.ndim
dis

2

In [191]:
space_of_array = np_x.nbytes
space_of_array

36

In [200]:
np_1 = np.array([1,2,4,56,7,0])
max_num_index = np.argmax(np_1)
max_num_index

3

In [201]:
min_num_index = np.argmin(np_1)
min_num_index

5

In [202]:
sort_index = np.argsort(np_1)
sort_index

array([5, 0, 1, 2, 4, 3], dtype=int64)

In [223]:
np_x[2,2]=4

In [224]:
np_x.argmax()

7

In [225]:
np_x.argmin()

0

In [228]:
np_x.argmax(axis=0)

array([2, 2, 1], dtype=int64)

In [229]:
np_x.argmax(axis=1)

array([2, 2, 1], dtype=int64)

In [234]:
np_x.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]], dtype=int64)

In [235]:
np_x.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

In [232]:
np_x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 4]])