In [89]:
!pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
import numpy as np

##### Simple one dimensional numpy array with integers from 1 to 9

This code creates a NumPy array with elements from 1 to 9, using 32-bit integers as the data type. It first prints the type of the array, which is `numpy.ndarray`, indicating that it's a NumPy array. Then, it prints the contents of the array, showing the sequence of numbers `[1 2 3 4 5 6 7 8 9]`.

In [91]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], np.int32)
print(type(np_array))
print(np_array)
                

<class 'numpy.ndarray'>
[1 2 3 4 5 6 7 8 9]


This code creates a 2D NumPy array with three rows and four columns. Each sublist in the array represents a row of the matrix. The `np_array_2d` variable holds the array, which looks like a 3x4 matrix when displayed. The structure is as follows:

```
[[ 1  2  3 12]
 [ 4  5  6 11]
 [ 7  8  9 10]]
```

This array can be used in various mathematical and data processing operations where a 2D structure is needed.

In [17]:
np_array_2d = np.array([[1, 2, 3, 12], [4, 5, 6, 11], [7, 8, 9, 10]])

np_array_2d


array([[ 1,  2,  3, 12],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 10]])

The `np_array_2d.dtype` attribute returns the data type of the elements in the `np_array_2d` NumPy array. 

### Example Explanation:
When you run `np_array_2d.dtype`, it will output the data type of the array elements. Since the array contains integers, the output will likely be `dtype('int64')` or `dtype('int32')`, depending on your system architecture. This indicates that the elements in `np_array_2d` are of type 64-bit or 32-bit integers.

Example output:
```python
dtype('int32')
```

This means that the elements in the `np_array_2d` array are stored as 32-bit integers.

In [93]:
np_array_2d.dtype

dtype('int32')

The code retrieves the first row of a 2D NumPy array and stores it in the variable `index_`. This means `index_` will contain the values from the first row of the array.

In [94]:
index_ = np_array_2d[0]
index_

array([ 1,  2,  3, 12])

This code finds the maximum value in the 2D NumPy array and stores it in the variable `maximum`. When you print `maximum`, it will display the largest value from all the elements in the array.

In [18]:
maximum = np_array_2d.max()
maximum

12

This code finds the minimum value in the 2D NumPy array and stores it in the variable `minimum`. When you print `minimum`, it will show the smallest value among all the elements in the array.

In [96]:
minimum = np_array_2d.min()
minimum

1

This code calculates the sum of all the elements in the 2D NumPy array and stores it in the variable `sum_of_array`. When you print `sum_of_array`, it will display the total sum of all values in the array.

In [97]:
sum_of_array = np_array_2d.sum()
sum_of_array

78

In [19]:
mean_ = np_array_2d.mean()
mean_

6.5

In [82]:
m_1 = np.array([[1, 3, 5],
                [2, 6, 9],
                [0, 4, 7]
                ])
m_2 = np.array([[4, 3, 1],
                [7, 3, 1],
                [4, 2, 3]
                ])
m_1 + m_2

array([[ 5,  6,  6],
       [ 9,  9, 10],
       [ 4,  6, 10]])

In [83]:
m_1 * m_2

array([[ 4,  9,  5],
       [14, 18,  9],
       [ 0,  8, 21]])

In [84]:
m_1 - m_2

array([[-3,  0,  4],
       [-5,  3,  8],
       [-4,  2,  4]])

In [85]:
m_1 / m_2

array([[0.25      , 1.        , 5.        ],
       [0.28571429, 2.        , 9.        ],
       [0.        , 2.        , 2.33333333]])

In [86]:
np.sqrt(m_1)

array([[1.        , 1.73205081, 2.23606798],
       [1.41421356, 2.44948974, 3.        ],
       [0.        , 2.        , 2.64575131]])

In [96]:
np.concatenate((m_1, m_2))

array([[1, 3, 5],
       [2, 6, 9],
       [0, 4, 7],
       [4, 3, 1],
       [7, 3, 1],
       [4, 2, 3]])

In [87]:
np.std(m_1)

2.7666443551086073

In [89]:
m_1

array([[1, 3, 5],
       [2, 6, 9],
       [0, 4, 7]])

In [88]:
np.transpose(m_1)

array([[1, 2, 0],
       [3, 6, 4],
       [5, 9, 7]])

In [91]:
m_1.T

array([[1, 2, 0],
       [3, 6, 4],
       [5, 9, 7]])

In [100]:
# np.linalg.inv(m_1)
# np.linalg.eig(m_1)
# np.linalg.det(m_1)
np.vstack((m_1, m_2))
# np./hstack((m_1, m_2))

array([[1, 3, 5],
       [2, 6, 9],
       [0, 4, 7],
       [4, 3, 1],
       [7, 3, 1],
       [4, 2, 3]])

This code extracts all elements from the 2D NumPy array that are greater than `5` and stores them in the variable `i`. When you print `i`, it will display a 1D array containing only the values from the original array that are greater than `5`.

In [99]:
i = np_array_2d[np_array_2d > 5]
i

array([12,  6, 11,  7,  8,  9, 10])

This code retrieves the shape of the 2D NumPy array and stores it in the variable `a`. The shape of an array is a tuple representing its dimensions. The `print` statement will show the dimensions of the array, indicating the number of rows and columns. For example, if the array has 3 rows and 4 columns, `a` will be `(3, 4)`.

In [100]:
a = np_array_2d.shape

print("Shape of the array:", a)

Shape of the array: (3, 4)


This code calculates the total number of elements in the 2D NumPy array and stores it in the variable `size`. When you print `size`, it will display the total count of elements in the array. For a 3x4 array, the output will be `12`, indicating there are 12 elements in total.

In [101]:
size = np_array_2d.size
size

12

This code reshapes the original 2D NumPy array into a new shape with 2 rows and 6 columns, and stores it in the variable `reshaped_array`. The `reshape` function rearranges the elements of the array to fit the new shape, while preserving the total number of elements. When you print `reshaped_array`, it will display the array in its new shape.

In [175]:
reshaped_array = np_array_2d.reshape(2, 6)
reshaped_array

array([[ 1,  2,  3, 12,  4,  5],
       [ 6, 11,  7,  8,  9, 10]])

This code flattens the 2D NumPy array into a 1D array and stores it in the variable `reshaped_array`. The `np.ravel` function returns a contiguous flattened array. When you print `reshaped_array`, it will display all the elements of the original array in a single, one-dimensional sequence.

In [176]:
reshaped_array = np.ravel(np_array_2d)
reshaped_array

array([ 1,  2,  3, 12,  4,  5,  6, 11,  7,  8,  9, 10])

In [177]:
reshaped_array = np_array_2d.ravel()
reshaped_array

array([ 1,  2,  3, 12,  4,  5,  6, 11,  7,  8,  9, 10])

In [80]:
zero_array = np.array([[0, 1, 2, 3], [5, 0, 4, 7]])
find_non_0 = np.nonzero(zero_array)
find_non_0

(array([0, 0, 0, 1, 1, 1], dtype=int64),
 array([1, 2, 3, 0, 2, 3], dtype=int64))

In [81]:
find_non_0 = np.count_nonzero(zero_array)
find_non_0

6

#### Numpy Array Creation

This code converts a Python list, `listarray`, into a NumPy array and stores it in the variable `np_array`. When you print `np_array`, it will display the list elements as a NumPy array. 

In [103]:
listarray = [1, 2, 3, 4, 5]
np_array = np.array(listarray)
np_array

array([1, 2, 3, 4, 5])

This code converts the values of a dictionary, `dic_array`, into a NumPy array and stores it in the variable `np_array_from_dict`. The `dic_array.values()` method extracts the dictionary values, and `np.array()` converts them into a NumPy array.


 OR convert the dictionary to a list and then to an array using `np.array(list(dic_array.values()))` and its not for only dictionary its work with `set` and `tuple`


In [112]:
dic_array = {'a': 1, 'b': 2, 'c': 3}

np_array_from_dict = np.array(dic_array.values())

np_array_from_dict

array(dict_values([1, 2, 3]), dtype=object)

This code converts a Python set, `set_array`, into a NumPy array and stores it in the variable `np_array_from_set`. Sets automatically remove duplicate elements, so any duplicates in `set_array` are eliminated.


In [111]:
set_array = {1, 2, 3, 4, 5, 5}
np_array_from_set = np.array(set_array)
np_array_from_set

array({1, 2, 3, 4, 5}, dtype=object)

This code converts a Python tuple, `tuple_array`, into a NumPy array and stores it in the variable `np_array_from_tuple`. 


In [110]:
tuple_array = (1, 2, 3, 4, 5)
np_array_from_tuple = np.array(tuple_array)
np_array_from_tuple

array([1, 2, 3, 4, 5])

This code creates a 3x3 NumPy array filled with zeros and stores it in the variable `zeros`. The `np.zeros` function generates an array of the specified shape, with all elements initialized to `0`.


In [113]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

This code creates two NumPy arrays Methods using the `np.arange` function:

1. **`range_array`**: This array contains values from `0` to `9` (10 is excluded), generated by `np.arange(10)`.

2. **`spa_range`**: This array contains values starting from `1` up to `9` (10 is excluded) with a step size of `2`, generated by `np.arange(1, 10, 2)`.


In [136]:
range_array = np.arange(10)
spa_range =  np.arange(1, 10, 2)

range_array, spa_range

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 3, 5, 7, 9]))

This code creates a NumPy array with `5` evenly spaced values between `1` and `10` (inclusive) using `np.linspace`.

The `linspace_array` Output will be:

```
[ 1.   3.25  5.5  7.75 10.  ]
```

`np.linspace(1, 10, 5)` generates an array where the values are linearly spaced between `1` and `10`, with a total of `5` points.

In [128]:
linspace_array = np.linspace(1, 10, 5)
linspace_array

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

This code creates a 2x3 NumPy array with uninitialized values using `np.empty`. The contents of the array are not set to any specific value and can contain arbitrary data based on the memory state.


In [164]:
empty_array = np.empty((2, 3))
empty_array

array([[4.24399158e-314, 2.54639495e-313, 1.06099790e-313],
       [2.33419537e-313, 1.69759663e-313, 2.12199579e-313]])

This code fills the previously created empty NumPy array with `0` using the `fill` method. After calling `empty_array.fill(0)`, all elements in the `empty_array` will be set to `0`.


In [162]:
empty_array.fill(0)
empty_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

This code creates a new NumPy array, `empty_like_array`, with the same shape and data type as `linspace_array`, but with uninitialized values. The `np.empty_like` function is used to generate this array.

In [166]:
empty_like_array = np.empty_like(linspace_array)
empty_like_array

array([7.88152004e-312, 7.88213896e-312, 6.95246149e-310, 0.00000000e+000,
       0.00000000e+000])

This code creates a 3x3 NumPy array where all elements are initialized to `1` using `np.ones`.

In [167]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

####  **np.identity VS np.eye**

This code creates a 3x3 identity matrix using `np.identity`. An identity matrix is a square matrix with `1`s on the main diagonal and `0`s elsewhere.


In [168]:
with_num_array = np.identity(3)
with_num_array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [169]:
with_num_array.shape

(3, 3)

This code creates a 3x3 identity matrix using `np.eye`. The `np.eye` function generates a square matrix with `1`s on the main diagonal and `0`s elsewhere, similar to `np.identity`.

In [170]:
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Both `np.eye` and `np.identity` are used to create identity matrices in NumPy, but they have some differences in their usage:

**`np.eye:`**
- **Usage**: `np.eye(N, M=None, k=0, dtype=<class 'float'>)`
- **Parameters**:
  - `N`: Number of rows in the matrix.
  - `M`: Number of columns in the matrix (if `None`, defaults to `N` to create a square matrix).
  - `k`: Diagonal offset. The default value `0` creates the main diagonal. A value of `1` creates the diagonal above the main diagonal, `-1` creates the diagonal below the main diagonal, and so on.
  - `dtype`: Data type of the matrix.
- **Functionality**: Creates a matrix with `1`s on the `k`-th diagonal and `0`s elsewhere. If `M` is not specified, it creates a square matrix with `N` rows and columns.

 **`np.identity:`**

- **Usage**: `np.identity(n, dtype=<class 'float'>)`
- **Parameters**:
  - `n`: The number of rows and columns in the square identity matrix.
  - `dtype`: Data type of the matrix.
- **Functionality**: Creates a square identity matrix with `n` rows and `n` columns. The `dtype` parameter specifies the type of the elements in the matrix.

 **Example**

- **Using `np.eye`**:
  ```python
  import numpy as np
  eye_matrix = np.eye(3)  # Creates a 3x3 identity matrix
  eye_matrix_with_offset = np.eye(3, k=1)  # Creates a matrix with 1s on the first upper diagonal
  ```

- **Using `np.identity`**:
  ```python
  import numpy as np
  identity_matrix = np.identity(3)  # Creates a 3x3 identity matrix
  ```

**Summary**
- `np.eye` is more flexible as it allows for non-square matrices and diagonal offsets.
- `np.identity` is simpler and specifically for creating square identity matrices.

#### **np.where()**

The `np.where` function in NumPy is used to find the indices of elements that satisfy a given condition or to return elements chosen from two arrays based on a condition. It is a versatile function with different use cases depending on the input parameters.

##### Basic Usage

1. **Finding Indices:**
   ```python
   np.where(condition)
   ```
   - **Parameters:**
     - `condition`: A boolean array or expression that specifies which elements to find.
   - **Returns:**
     - The indices of elements where the condition is `True`. It returns a tuple of arrays, one for each dimension of the input array.

   **Example:**
   ```python
   import numpy as np
   array = np.array([10, 20, 30, 40, 50])
   indices = np.where(array > 25)
   print(indices)
   ```
   - **Output:**
     ```
     (array([2, 3, 4]),)
     ```
   This indicates that elements greater than 25 are at indices 2, 3, and 4 in the `array`.

2. **Conditional Selection:**
   ```python
   np.where(condition, x, y)
   ```
   - **Parameters:**
     - `condition`: A boolean array or expression.
     - `x`: Values to be chosen where the condition is `True`.
     - `y`: Values to be chosen where the condition is `False`.
   - **Returns:**
     - An array with values from `x` where `condition` is `True`, and values from `y` where `condition` is `False`.

   **Example:**
   ```python
   import numpy as np
   array = np.array([1, 2, 3, 4, 5])
   result = np.where(array % 2 == 0, 'Even', 'Odd')
   print(result)
   ```
   - **Output:**
     ```
     ['Odd' 'Even' 'Odd' 'Even' 'Odd']
     ```
   This replaces even numbers with 'Even' and odd numbers with 'Odd'.

##### Summary

- **Finding Indices**: Use `np.where(condition)` to get the indices of elements that meet the specified condition.
- **Conditional Selection**: Use `np.where(condition, x, y)` to create a new array where values are chosen based on the condition.

This code finds the indices of even numbers in the `nonlocal_array` using the `np.where` function.

- **`Explanation`**

- **`nonlocal_array % 2 == 0`**: This condition checks which elements of `nonlocal_array` are even. The result is a boolean array where `True` indicates an even number.

- **`np.where(...)`**: This function returns the indices of elements that satisfy the given condition.

- **`Output`**

The `match_` will contain the indices of the even numbers in `nonlocal_array`. For the array `[1, 2, 3, 4, 5, 6, 7, 8, 9]`, the even numbers are `2, 4, 6, 8`, which are located at indices `1, 3, 5, 7`.

So, the output of `match_` will be:

```
(array([1, 3, 5, 7]),)
```

This indicates that the even numbers are located at indices 1, 3, 5, and 7 in the original array.

In [53]:
local_array = np.array([[1, 2, 9, 4],[5, 6, 7, 8]])
match_ = np.where(local_array % 2 == 0)
match_

(array([0, 0, 1, 1], dtype=int64), array([1, 3, 1, 3], dtype=int64))

This code finds the indices of the element `5` in the 2D NumPy array and stores them in `find_index`. The `np.where` function returns the positions where the condition (element equals `5`) is true. The result, `find_index`, contains the row and column indices of the element `5`. The `print` statement will show these indices.

In [54]:
find_index = np.where(local_array == 5)

print("Index of the number 5:", find_index)

Index of the number 5: (array([1], dtype=int64), array([0], dtype=int64))


In [55]:
find_item = np.where(local_array >5)
find_item

(array([0, 1, 1, 1], dtype=int64), array([2, 1, 2, 3], dtype=int64))

#### Numpy AIXS

In [178]:
x = [[1,2,3], [4,5,6], [7,8,9]]

np_x = np.array(x)
np_x


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The code calculates the sum of elements along a specific axis of a NumPy array `np_x`. Here's what it does:

- **`np_x.sum(axis=0)`**:
  - **`axis=0`**: Specifies that the sum should be computed along the vertical axis (i.e., column-wise) of the array. This means the function will sum up the elements in each column.


  This result means:
  - The sum of the first column (1 + 4 + 7) is `12`.
  - The sum of the second column (2 + 5 + 8) is `15`.
  - The sum of the third column (3 + 6 + 9) is `18`.


In [184]:
sum_of_axis_0 = np_x.sum(axis=0)
sum_of_axis_0

array([12, 15, 18])

The code calculates the sum of elements along a specific axis of the NumPy array `np_x`, with `axis=1` indicating that the summation should be done along the horizontal axis (i.e., row-wise).

- **`np_x.sum(axis=1)`**:
  - **`axis=1`**: Specifies that the sum should be computed along the rows. This means the function will sum up the elements in each row.

  This result means:
  - The sum of the first row (1 + 2 + 3) is `6`.
  - The sum of the second row (4 + 5 + 6) is `15`.
  - The sum of the third row (7 + 8 + 9) is `24`.

In [185]:
sum_of_axis_1 = np_x.sum(axis=1)
sum_of_axis_1

array([ 6, 15, 24])

The code transposes the 2D NumPy array `np_x` and stores the result in the variable `tran_mat`. Transposing an array means swapping its rows and columns.

- **`np_x.T`**: This is a shorthand for the transpose of the array `np_x`. It switches the array's rows with its columns.

  This result means:
  - The first row of `tran_mat` corresponds to the first column of `np_x`.
  - The second row of `tran_mat` corresponds to the second column of `np_x`.
  - The third row of `tran_mat` corresponds to the third column of `np_x`.

In [186]:
tran_mat = np_x.T
tran_mat

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

The `np_x.flat` attribute provides a 1D iterator over the elements of the NumPy array `np_x`. It allows you to iterate over the array's elements as if the array were flattened into a single dimension.

- **`np_x.flat`**: Provides an iterator over the flattened version of `np_x`.

This means you can access all elements of `np_x` in a single-dimensional sequence, which is useful for iterating through the entire array in a flat manner.

In [187]:
np_x.flat

In [188]:
for item in np_x.flat:
    print(item)

1
2
3
4
5
6
7
8
9


The code `np_x.ndim` returns the number of dimensions (axes) of the NumPy array `np_x`. This attribute tells you how many dimensions the array has.

- **`np_x.ndim`**: Returns the number of dimensions of `np_x`.

This means `np_x` is a 2-dimensional array. If `np_x` were a 3D array, `np_x.ndim` would return `3`, and so on.

In [189]:
dis = np_x.ndim
dis

2

The code `np_x.nbytes` returns the total number of bytes used to store the NumPy array `np_x` in memory. This is the product of the array's size (number of elements) and the size of each element in bytes.


Assuming the array is of type `int64` (which uses 4 bytes per element), and it has 9 elements:

- **`np_x.nbytes`**: Calculates the total memory usage in bytes.

  This result is computed as:
  - Number of elements: 9
  - Size of each element: 4 bytes (for `int64`)
  - Total size: 9 elements × 4 bytes/element = 36 bytes

In [191]:
space_of_array = np_x.nbytes
space_of_array

36

The code `np.argmax(np_1)` returns the index of the maximum value in the NumPy array `np_1`. 


- **`np.argmax(np_1)`**: Finds the index of the first occurrence of the maximum value in the array `np_1`.
- **`np.argmax(np_1)`**: Returns the index of the maximum value in `np_1`.


  Here, `56` is the maximum value, and it is located at index `3` in the array.

In [200]:
np_1 = np.array([1,2,4,56,7,0])
max_num_index = np.argmax(np_1)
max_num_index

3

The code `np.argmin(np_1)` returns the index of the minimum value in the NumPy array `np_1`. 


- **`np.argmin(np_1)`**: Finds the index of the first occurrence of the minimum value in the array `np_1`.
- **`np.argmin(np_1)`**: Returns the index of the minimum value in `np_1`.


  Here, `0` is the minimum value, and it is located at index `5` in the array.

In [201]:
min_num_index = np.argmin(np_1)
min_num_index

5

The code `np.argsort(np_1)` returns the indices that would sort the array `np_1` in ascending order. It provides a 1D array of indices that can be used to reorder `np_1` such that the values are sorted.

- **`np.argsort(np_1)`**: Returns the indices that would sort `np_1`.

  This output means:
  - The smallest value `0` is at index `5`.
  - The second smallest value `1` is at index `0`.
  - The third smallest value `2` is at index `1`.
  - And so on.


In [202]:
sort_index = np.argsort(np_1)
sort_index

array([5, 0, 1, 2, 4, 3], dtype=int64)

In [223]:
np_x[2,2]=4

Here is the `np_x` two 2D array . When youo apply the `np_x.argmax()` then First the array change 1D array and find the max value. return the index of the max value

In [224]:
np_x.argmax()

7

Here is the `np_x` two 2D array . When youo apply the `np_x.argmin()` then First the array change 1D array and find the min value. return the index of the min value

In [225]:
np_x.argmin()

0

The code `np_x.argmax(axis=0)` returns the indices of the maximum values along the specified axis of the NumPy array `np_x`. In this case, `axis=0` specifies that the operation should be performed along the vertical axis (i.e., column-wise).

- **`np_x.argmax(axis=0)`**: Finds the indices of the maximum values in each column of the array `np_x`.

  This means:
  - The maximum value in the first column (1, 4, 7) is at index `2` (value `7`).
  - The maximum value in the second column (2, 5, 8) is at index `2` (value `8`).
  - The maximum value in the third column (3, 6, 4) is at index `1` (value `6`).

In [228]:
np_x.argmax(axis=0)

array([2, 2, 1], dtype=int64)

The code `np_x.argmax(axis=1)` returns the indices of the maximum values along the specified axis of the NumPy array `np_x`. In this case, `axis=0` specifies that the operation should be performed along the vertical axis (i.e., column-wise).


- **`np_x.argmax(axis=1)`**: Finds the indices of the maximum values in each column of the array `np_x`.

  This means:
  - The maximum value in the first column (1, 2, 3) is at index `2` (value `3`).
  - The maximum value in the second column (4, 5, 6) is at index `2` (value `6`).
  - The maximum value in the third column (7, 8, 4) is at index `1` (value `8`).

In [229]:
np_x.argmax(axis=1)

array([2, 2, 1], dtype=int64)

The code `np_x1.argsort(axis=0)` returns the indices that would sort the array `np_x1` along the vertical axis (i.e., column-wise).

- **`np_x1.argsort(axis=0)`**: Computes the indices that would sort each column of `np_x1` in ascending order.

  This means:
  - In the first column `[1, 4, 7]`, the sorted order is `[1, 4, 7]`, so the indices are `[0, 1, 2]`.
  - In the second column `[2, 5, 8]`, the sorted order is `[2, 5, 8]`, so the indices are `[0, 1, 2]`.
  - In the third column `[3, 6, 4]`, the sorted order is `[3, 4, 6]`, so the indices are `[0, 2, 1]`.

In [22]:
np_x1 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,4]])
np_x1.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 2],
       [2, 2, 1]], dtype=int64)

The code `np_x1.argsort(axis=1)` returns the indices that would sort the array `np_x1` along the horizontal axis (i.e., row-wise).

- **`np_x1.argsort(axis=1)`**: Computes the indices that would sort each row of `np_x1` in ascending order.
- **`np_x1.argsort(axis=1)`**: Returns the indices that would sort each row.

  **Output:**

  ```python
  array([[0, 1, 2],
         [0, 1, 2],
         [0, 2, 1]])
  ```

  This means:
  - In the first row `[1, 2, 3]`, the sorted order is `[1, 2, 3]`, so the indices are `[0, 1, 2]`.
  - In the second row `[4, 5, 6]`, the sorted order is `[4, 5, 6]`, so the indices are `[0, 1, 2]`.
  - In the third row `[7, 8, 4]`, the sorted order is `[4, 7, 8]`, so the indices are `[2, 0, 1]`.

In [34]:
print(np_x1)
np_x1.argsort(axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 4]]


array([[0, 1, 2],
       [0, 1, 2],
       [2, 0, 1]], dtype=int64)

array([[ 4,  9,  5],
       [14, 18,  9],
       [ 0,  8, 21]])

In [37]:
m_1 - m_2

array([[-3,  0,  4],
       [-5,  3,  8],
       [-4,  2,  4]])

In [38]:
m_1 / m_2

array([[0.25      , 1.        , 5.        ],
       [0.28571429, 2.        , 9.        ],
       [0.        , 2.        , 2.33333333]])

In [39]:
np.sqrt(m_1)

array([[1.        , 1.73205081, 2.23606798],
       [1.41421356, 2.44948974, 3.        ],
       [0.        , 2.        , 2.64575131]])